dist: xenial
os: linux
language: node_js
node_js: lts/dubnium
cache: yarn
services:
  - docker

before_install:
  - git clone --depth=1 --branch=cpk-test https://github.com/gnosis/safe-relay-service.git

before_script:
  - cd safe-relay-service
  - docker-compose -f docker-compose.yml -f docker-compose.dev.yml build
  - SAFE_RELAY_CONTAINER_ID=$(docker-compose -f docker-compose.yml -f docker-compose.dev.yml up -d)
  - cd ..

after_script:
  - cd safe-relay-service
  - docker-compose down
  - cd ..
  - docker logs $PROVIDER_CONTAINER_ID
  - docker stop $PROVIDER_CONTAINER_ID
  - docker rm $PROVIDER_CONTAINER_ID

jobs:
  include:
  - name: Ganache
    before_script:
      - PROVIDER_CONTAINER_ID=$(docker run -d -p 8545:8545 trufflesuite/ganache-cli --defaultBalanceEther 10000)
      - yarn wait-port -t 10000 localhost:8545

  - name: Ganache with --noVMErrorsOnRPCResponse
    before_script:
      - PROVIDER_CONTAINER_ID=$(docker run -d -p 8545:8545 trufflesuite/ganache-cli --defaultBalanceEther 10000 --noVMErrorsOnRPCResponse)
      - yarn wait-port -t 10000 localhost:8545

  - name: Geth
    before_script:
     - yarn geth-dev-assistant --accounts 10 --gasLimit 6721975 --balance 10000
     - PROVIDER_CONTAINER_ID=geth-client

  - name: OpenEthereum
    before_script:
      - PASSFILE=$(mktemp)
      - echo '' > $PASSFILE
      - chmod 644 $PASSFILE
      - PROVIDER_CONTAINER_ID=$(docker run -d -p 8545:8545 -p 8546:8546 -v $PASSFILE:$PASSFILE openethereum/openethereum --config dev --jsonrpc-interface=all --ws-interface=all --unlock 0x00a329c0648769a73afac7f9381e08fb43dbea72 --password $PASSFILE)
      - yarn wait-port -t 10000 localhost:8545

after_success: yarn coverage
